### PR TITLE
CB-13-company-news

### PR DESCRIPTION
**Pull request by DHua5922**
* **Please check if the PR fulfills these requirements**
- [X] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)

New feature: component for showing company news

* **What is the current behavior?What does the code do before you made the new changes?** 

No component for showing company news

* **What is the new behavior?**

There is now a component for showing company news.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)

Install [date-fns](https://date-fns.org/) by `npm i date-fns`

* **Other information**:

This code shows the company news based on hardcoded data. Once the news API in the back end has been completed, this code will need to be updated by having the code call the news API.

### CODE REVIEW

**Review by sunnyguan — APPROVED** [review]
Looks good, test works too.

**Review by maahasakhia — COMMENTED** [review]
I think it looks fine

**Review by Codubee — APPROVED** [review]
LGTM!

**Comment by Codubee** [comment]
Great work Dylan. Just the merge conflict and we can merge.

**Pull request merged**
